# Generated by Django 4.1.3 on 2022-11-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovely_trees_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='species_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovely_trees_api.species'),
        ),
    ]
