# Generated by Django 4.1.3 on 2022-11-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovely_trees_api', '0002_alter_fielddata_species_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='health',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Ok'), (3, 'Excellent')], null=True),
        ),
    ]
